/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.individual;

import business.HealthSystem;
import business.enterprise.Enterprise;
import business.enterprise.Hospital;
import business.network.Network;
import business.organization.Organization;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author darshak
 */
public class SelectHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectHospitalJPanel
     */
    private JPanel container;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private HealthSystem system;
    
    private Enterprise selectHospital;
    public SelectHospitalJPanel(JPanel container,UserAccount userAccount,Organization organization,
            Enterprise enterprise,HealthSystem system) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        
        popTree();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void popTree(){
        
        DefaultTreeModel model = (DefaultTreeModel) selectHospitalJTree.getModel();
        DefaultMutableTreeNode root =(DefaultMutableTreeNode) model.getRoot();
        
        Network country = enterprise.findNetwork(system, enterprise).get(0);
        DefaultMutableTreeNode nation = new DefaultMutableTreeNode(country);
        root.removeAllChildren();
        root.insert(nation, 0);
        
        
        for(int i = 0;i<country.getNetworkList().size();i++){
            Network state = country.getNetworkList().get(i);
            //create network node
            DefaultMutableTreeNode stateNode = new DefaultMutableTreeNode(state);
            nation.insert(stateNode, i);
            
            for(int j = 0; j<state.getNetworkList().size();j++){
                Network city = state.getNetworkList().get(j);
                DefaultMutableTreeNode cityNode = new DefaultMutableTreeNode(city);
                stateNode.insert(cityNode, j);
                
                for(int k = 0; k<city.getEnterpriseList().size();k++){
                    Enterprise e = city.getEnterpriseList().get(k);
                    if(e instanceof Hospital){
                        int m = 0;
                        DefaultMutableTreeNode enterpriseNode = new DefaultMutableTreeNode(e);
                        cityNode.insert(enterpriseNode, m);
                        m++;
                    }
                    
                }
            }
        }
        //reload the tree
        model.reload();
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectHospitalJTree = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        selectedHospitalJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        nextJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Report: Step 1: Select report concerned hospital");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Nationwide");
        selectHospitalJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        selectHospitalJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                selectHospitalJTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(selectHospitalJTree);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("You selected hospital:");

        selectedHospitalJTextField.setEditable(false);

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        nextJButton.setText("Next");
        nextJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nextJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(selectedHospitalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(selectedHospitalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backJButton)
                            .addComponent(nextJButton))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectHospitalJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_selectHospitalJTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectNode = (DefaultMutableTreeNode)selectHospitalJTree.getLastSelectedPathComponent();
        if(selectNode == null) return;
        selectHospital = null;
        try{
            selectHospital=(Enterprise) selectNode.getUserObject();
            selectedHospitalJTextField.setText(selectHospital.toString());
        }catch(ClassCastException cce){
            
        }
        
    }//GEN-LAST:event_selectHospitalJTreeValueChanged

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void nextJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJButtonActionPerformed
        // TODO add your handling code here:
        IndividualReportStepOneJPanel irsojp = new IndividualReportStepOneJPanel(container,
                userAccount,organization,enterprise,selectHospital,system);
        container.add("IndividualReportStepOneJPanel", irsojp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_nextJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextJButton;
    private javax.swing.JTree selectHospitalJTree;
    private javax.swing.JTextField selectedHospitalJTextField;
    // End of variables declaration//GEN-END:variables
}
