/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.government;

import business.HealthSystem;
import business.report.BasicInfo;
import business.report.PatientInfo;
import business.report.Product;
import business.report.ProductInfo;
import business.report.Report;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author darshak
 */
public class ShowReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowReportJPanel
     */
    private JPanel container;
//    private Report report;
//    private HealthSystem system;
    
    private BasicInfo basic;
    private PatientInfo patient;
    private ProductInfo products;
    public ShowReportJPanel(JPanel container,Report report,HealthSystem system) {
        initComponents();
        this.container = container;
//        this.report = report;
//        this.system = system;
        
        basic = report.getBasic();
        patient = report.getPatient();
        products = report.getProduct();
        
        stateJLabel.setText(basic.getHospital().findNetwork(system, basic.getHospital()).get(1).getName());
        cityJLabel.setText(basic.getHospital().findNetwork(system, basic.getHospital()).get(2).getName());
        
        printData();
        popTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void printData(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
        
        discoverDateJFormattedTextField.setValue(sdf.format(basic.getDiscoverDate().getTime()));
        reportDateJFormattedTextField.setValue(sdf.format(basic.getReportDate().getTime()));
        if(basic.getInvolved().equals(BasicInfo.YES)){
            involvedYesJRadioButton.setSelected(true);
        }else{
            involvedNoJRadioButton.setSelected(true);
        }
        placeJTextField.setText(basic.getPlace());
        hospitalNameJTextField.setText(basic.getHospital().getName());
        if(basic.getEventCategories().contains(BasicInfo.DEVICE)){
            deviceJCheckBox.setSelected(true);
        }
        if(basic.getEventCategories().contains(BasicInfo.HUMAN)){
            humanJCheckBox.setSelected(true);
        }
        if(basic.getEventCategories().contains(BasicInfo.MEDICATION)){
            medicationJCheckBox.setSelected(true);
        }
        if(basic.getEventCategories().contains(BasicInfo.OTHER)){
            otherJCheckBox.setSelected(true);
        }
        preventabilityJTextField.setText(basic.getPreventability());
        descriptionJTextArea.setText(basic.getDescription());
        
        mrnJTextField.setText(String.valueOf(patient.getMrn()));
        nameJTextField.setText(patient.getName());
        genderJTextField.setText(patient.getGender());
        raceJTextField.setText(patient.getRace());
        dobJFormattedTextField.setValue(sdf.format(patient.getDob().getTime()));
        diagnosisJTextField.setText(patient.getDiagnosis());
        primaryDoctorJTextField.setText(patient.getPrimaryPgysician());
        harmDegreeJTextField.setText(patient.getHarmDegree().toString());
        
    }
    
    private void popTableData(){
        int rowCount = productsJTable.getRowCount();
        for(int i=rowCount-1; i>=0; i--){
            ((DefaultTableModel)productsJTable.getModel()).removeRow(i);
        }
        for(Product p : products.getProductList()){
            Object row[] = new Object[2];
            row[0] = p;
            row[1] = p.getProductType();
            
            ((DefaultTableModel)productsJTable.getModel()).addRow(row);  
        }
    }
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        stateJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaskFormatter mf = null;
        try {
            mf = new MaskFormatter("####-##-##");
        } catch (ParseException p) {
            p.printStackTrace();
        }
        discoverDateJFormattedTextField = new javax.swing.JFormattedTextField(mf);
        placeJTextField = new javax.swing.JTextField();
        involvedNoJRadioButton = new javax.swing.JRadioButton();
        involvedYesJRadioButton = new javax.swing.JRadioButton();
        reportDateJFormattedTextField = new javax.swing.JFormattedTextField(mf);
        jLabel8 = new javax.swing.JLabel();
        deviceJCheckBox = new javax.swing.JCheckBox();
        humanJCheckBox = new javax.swing.JCheckBox();
        medicationJCheckBox = new javax.swing.JCheckBox();
        otherJCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mrnJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        raceJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dobJFormattedTextField = new javax.swing.JFormattedTextField(mf);
        jLabel16 = new javax.swing.JLabel();
        diagnosisJTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        primaryDoctorJTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        productsJTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        hospitalNameJTextField = new javax.swing.JTextField();
        preventabilityJTextField = new javax.swing.JTextField();
        genderJTextField = new javax.swing.JTextField();
        harmDegreeJTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Report");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("The report is sent from");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        stateJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stateJLabel.setText("<<State>>");

        cityJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cityJLabel.setText("<<City>>");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("Basic Info");

        jLabel2.setText("Discover Date");

        jLabel3.setText("Report Date");

        jLabel4.setText("Involved");

        jLabel5.setText("Occured place");

        discoverDateJFormattedTextField.setEditable(false);

        placeJTextField.setEditable(false);

        involvedNoJRadioButton.setText("No");
        involvedNoJRadioButton.setEnabled(false);

        involvedYesJRadioButton.setText("Yes");
        involvedYesJRadioButton.setEnabled(false);

        reportDateJFormattedTextField.setEditable(false);

        jLabel8.setText("Event categories");

        deviceJCheckBox.setText("Device");
        deviceJCheckBox.setEnabled(false);

        humanJCheckBox.setText("Human Error");
        humanJCheckBox.setEnabled(false);

        medicationJCheckBox.setText("Medication");
        medicationJCheckBox.setEnabled(false);

        otherJCheckBox.setText("Other");
        otherJCheckBox.setEnabled(false);

        jLabel7.setText("Preventability");

        jLabel6.setText("Description");

        descriptionJTextArea.setEditable(false);
        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionJTextArea);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Patient Info");

        jLabel11.setText("M R N");

        mrnJTextField.setEditable(false);

        jLabel12.setText("Name");

        nameJTextField.setEditable(false);

        jLabel13.setText("Gender");

        jLabel14.setText("Race");

        raceJTextField.setEditable(false);

        jLabel15.setText("DOB");

        dobJFormattedTextField.setEditable(false);

        jLabel16.setText("Diagnosis");

        diagnosisJTextField.setEditable(false);

        jLabel17.setText("Primary Doctor");

        primaryDoctorJTextField.setEditable(false);

        jLabel18.setText("Harm Degree");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel19.setText("Product Info");

        productsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(productsJTable);

        jLabel20.setText("Hospital");

        hospitalNameJTextField.setEditable(false);

        preventabilityJTextField.setEditable(false);

        genderJTextField.setEditable(false);

        harmDegreeJTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addComponent(jLabel20))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reportDateJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hospitalNameJTextField)
                                            .addComponent(discoverDateJFormattedTextField)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(involvedYesJRadioButton)
                                                .addGap(44, 44, 44)
                                                .addComponent(involvedNoJRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(placeJTextField))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deviceJCheckBox)
                                            .addComponent(medicationJCheckBox))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(otherJCheckBox)
                                            .addComponent(humanJCheckBox)))
                                    .addComponent(jScrollPane1)
                                    .addComponent(preventabilityJTextField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mrnJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(raceJTextField)
                                    .addComponent(genderJTextField))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dobJFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addComponent(diagnosisJTextField))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(harmDegreeJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(primaryDoctorJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))))
                    .addComponent(jLabel19))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discoverDateJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(deviceJCheckBox)
                    .addComponent(humanJCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reportDateJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicationJCheckBox)
                    .addComponent(otherJCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(involvedNoJRadioButton)
                        .addComponent(involvedYesJRadioButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(preventabilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(placeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(hospitalNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mrnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(dobJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(diagnosisJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(primaryDoctorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(raceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(harmDegreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stateJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityJLabel))
                    .addComponent(backJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(stateJLabel)
                    .addComponent(cityJLabel))
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JCheckBox deviceJCheckBox;
    private javax.swing.JTextField diagnosisJTextField;
    private javax.swing.JFormattedTextField discoverDateJFormattedTextField;
    private javax.swing.JFormattedTextField dobJFormattedTextField;
    private javax.swing.JTextField genderJTextField;
    private javax.swing.JTextField harmDegreeJTextField;
    private javax.swing.JTextField hospitalNameJTextField;
    private javax.swing.JCheckBox humanJCheckBox;
    private javax.swing.JRadioButton involvedNoJRadioButton;
    private javax.swing.JRadioButton involvedYesJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox medicationJCheckBox;
    private javax.swing.JTextField mrnJTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JCheckBox otherJCheckBox;
    private javax.swing.JTextField placeJTextField;
    private javax.swing.JTextField preventabilityJTextField;
    private javax.swing.JTextField primaryDoctorJTextField;
    private javax.swing.JTable productsJTable;
    private javax.swing.JTextField raceJTextField;
    private javax.swing.JFormattedTextField reportDateJFormattedTextField;
    private javax.swing.JLabel stateJLabel;
    // End of variables declaration//GEN-END:variables
}
