/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.government;

import business.HealthSystem;
import Business.Analysis.Entry;
import business.organization.GovernmentAnalyst;
import business.organization.Organization;
import java.awt.CardLayout;
import java.util.HashSet;
import javax.swing.JPanel;

/**
 *
 * @author darshak
 */
public class SummaryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryJPanel
     */
    private JPanel container;
    private HashSet<Entry> entrySet1;
    private HashSet<Entry> entrySet2;
    
    public SummaryJPanel(JPanel container,Organization organization,HealthSystem system) {
        
        initComponents();
        this.container = container;
        
//        ((GovernmentAnalyst)organization).getKb().calculateRegionCount(system, organization.getWorkQueue());
        entrySet1 = ((GovernmentAnalyst)organization).getKb().calculateRegionCount(system, organization.getWorkQueue());
        entrySet2 = ((GovernmentAnalyst)organization).getKb().calculateCategoryCount(system, organization.getWorkQueue());
        RegionJPanel rj = new RegionJPanel(entrySet1);
        CategoryJPanel cj = new CategoryJPanel(entrySet2);
        jTabbedPane1.add("Region Analysis", rj);
        jTabbedPane1.add("Category Analysis",cj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Summary");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
