/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.government;

import business.HealthSystem;
import business.organization.Organization;
import business.userAccount.UserAccount;
import business.workQueue.ReportWorkRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darshak
 */
public class ViewReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewReportJPanel
     */
    private JPanel container;
//    private UserAccount userAccount;
    private Organization organization;
    private HealthSystem system;
    
    public ViewReportJPanel(JPanel container,Organization organization,HealthSystem system) {
        initComponents();
        this.container = container;
//        this.userAccount = userAccount;
        this.organization = organization;
        this.system = system;
        
        popTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void popTableData(){
        int rowCount = viewReportJTable.getRowCount();
        for(int i=rowCount-1; i>=0; i--){
            ((DefaultTableModel)viewReportJTable.getModel()).removeRow(i);
        }

        for(WorkRequest wr: organization.getWorkQueue().getWorkRequestList()){
            Object row[] = new Object[3];
            row[0] = wr;
            row[1] = wr.getSender();
            row[2] = ((ReportWorkRequest)wr).getReport();
            ((DefaultTableModel)viewReportJTable.getModel()).addRow(row);  
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewReportJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        showJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View Reports");

        viewReportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "Sender", "Event ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(viewReportJTable);

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        showJButton.setText("Show Detail");
        showJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(showJButton))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void showJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showJButtonActionPerformed
        int selectedRow = viewReportJTable.getSelectedRow();
        if(selectedRow>=0){
            WorkRequest wr = (WorkRequest)viewReportJTable.getValueAt(selectedRow, 0);
            wr.setStatus(WorkRequest.ARCHIAVE);
            ShowReportJPanel srjp = new ShowReportJPanel(container,((ReportWorkRequest)wr).getReport(),system);
            container.add("ShowReportJPanel", srjp);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        }else{
            JOptionPane.showConfirmDialog(null,"select one row please","Warning",
                    JOptionPane.YES_NO_OPTION);
        }
    }//GEN-LAST:event_showJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton showJButton;
    private javax.swing.JTable viewReportJTable;
    // End of variables declaration//GEN-END:variables
}
