/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.enterpriseAdmin;

import business.HealthSystem;
import business.enterprise.Enterprise;
import business.person.Person;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author darshak
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private HealthSystem system;
    public EnterpriseAdminWorkAreaJPanel(JPanel container,Enterprise enterprise,HealthSystem system) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.system = system;
        
        enterpriseNameJLabel.setText(enterprise.getName());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        manageOrgJButton = new javax.swing.JButton();
        managePersonJButton = new javax.swing.JButton();
        manageUserJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enterprise Admin Work Area");

        enterpriseNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseNameJLabel.setText("<<Name>>");

        manageOrgJButton.setText("Manage Organization");
        manageOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgJButtonActionPerformed(evt);
            }
        });

        managePersonJButton.setText("Manage Person");
        managePersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonJButtonActionPerformed(evt);
            }
        });

        manageUserJButton.setText("Manage User Account");
        manageUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(enterpriseNameJLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(manageOrgJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(managePersonJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manageUserJButton)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseNameJLabel))
                .addGap(18, 18, 18)
                .addComponent(manageOrgJButton)
                .addGap(18, 18, 18)
                .addComponent(managePersonJButton)
                .addGap(18, 18, 18)
                .addComponent(manageUserJButton)
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void manageOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrgJPanel mojp = new ManageOrgJPanel(container,enterprise);
        container.add("ManageOrgJPanel", mojp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageOrgJButtonActionPerformed

    private void managePersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonJButtonActionPerformed
        // TODO add your handling code here:
        ManagePersonJPanel mpjp = new ManagePersonJPanel(container,enterprise);
        container.add("ManagePersonJPanel", mpjp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_managePersonJButtonActionPerformed

    private void manageUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserJPanel mujp = new ManageUserJPanel(container,enterprise,system);
        container.add("ManageUserJPanel", mujp);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageUserJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrgJButton;
    private javax.swing.JButton managePersonJButton;
    private javax.swing.JButton manageUserJButton;
    // End of variables declaration//GEN-END:variables
}
